[package]
name = "rustfmsynth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15.2"
eframe = "0.26.2" # Latest version
rand = "0.8"
device_query = "1.1.3"

[lib]
path = "src/lib.rs"
